title: alexandermussell.com
author: Alexander Mussell
email: alex@alexandermussell.com
description: > 
  Start of a weekly blog. Mainly to track progress over the weeks. Expect changes as I move away from Jekyll.
show_excerpts: true 

sass:
  sass_dir: _sass
plainwhite:
  name: Alexander Mussell
  tagline: SRE. Weightlifting. Reading.
  date_format: "%b %-d, %Y"
  sitemap: false

  navigation:
    - title: Home
      url: "/"
    - title: Reading List
      url: "/reading-list"
    - title: Blog
      url: "/blog"

  social_links:
    github:  AlexMussell
    rss: rss

  # reading_list:
  #   beyond-good-and-evil: https://www.amazon.co.uk/Beyond-Good-Evil-Friedrich-Nietzsche/dp/1497415764

theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed