title: Alexander Mussell
author: Alexander Mussell
email: alex@alexandermussell.com
description: > 
  Even if nobody ever comes here, I learn best when trying to explain things to others. This is my attempt to do that.
show_excerpts: true

sass:
  sass_dir: _sass
plainwhite:
  name: Alexander Mussell
  tagline: Site Reliability Engineer
  date_format: "%b %-d, %Y"
  sitemap: false
  condensed_mobile:
    - home
  navigation:
    - title: Home
      url: "/"
#    - title: Reading List
#      url: "/reading-list"
    - title: Blog
      url: "/blog"
#    - title: Download Résumé
#      url: "/assets/AlexanderMussellCV.pdf"

  social_links:
    github:  AlexMussell
    rss: rss
    linkedIn: in/alexander-mussell-2812aa192
    email: alex@alexandermussell.com
# Build settings
remote_theme: plainwhite

paginate: 6
paginate_path: /blog/page:num/

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
