title: alexandermussell.com
author: Alexander Mussell
email: alex@alexandermussell.com
description: > 
  Start of a weekly blog. Mainly to track progress over the weeks. Expect changes as I move away from Jekyll.
show_excerpts: true 

sass:
  sass_dir: _sass
plainwhite:
  name: Alexander Mussell
  tagline: SRE. Weightlifting. Reading.
  date_format: "%b %-d, %Y"
  sitemap: false # set to true to generate sitemap.xml content

  navigation:
    - title: General
      url: "/general"
    - title: Reading List
      url: "/reading-list"

  # generate social links in footer
  social_links:
    github:  AlexMussell
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed