title: alexandermussell.com
author: Alexander Mussell
email: alex@alexandermussell.com
description: > 
  Welcome to my Blog! Where I track my technological journey and hopefully help a few people out along the way!
show_excerpts: true 

sass:
  sass_dir: _sass
plainwhite:
  name: Alexander Mussell
  tagline: SRE. Weightlifting. Reading.
  date_format: "%b %-d, %Y"
  sitemap: false

  navigation:
    - title: Home
      url: "/"
    - title: Reading List
      url: "/reading-list"
    - title: Blog
      url: "/blog"

  social_links:
    github:  AlexMussell
    rss: rss

# Build settings
remote_theme: plainwhite

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
